/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.radioButton;

import java.awt.event.ActionListener;

/**
 *
 * @author iglesias_nieto_rodrigo
 */
public class RadioButtonDialog extends javax.swing.JDialog {

    /**
     * Creates new form RadioButtonDialog
     */
    public RadioButtonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionGroup = new javax.swing.ButtonGroup();
        opcion1RadioButton = new javax.swing.JRadioButton();
        opcion2RadioButton = new javax.swing.JRadioButton();
        opcion3RadioButton = new javax.swing.JRadioButton();
        radioButtonLabel = new javax.swing.JLabel();
        getSelectedOptionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        optionGroup.add(opcion1RadioButton);
        opcion1RadioButton.setText("Opcion 1");
        opcion1RadioButton.setActionCommand("op1");

        optionGroup.add(opcion2RadioButton);
        opcion2RadioButton.setText("Opcion 2");
        opcion2RadioButton.setActionCommand("opt2");

        optionGroup.add(opcion3RadioButton);
        opcion3RadioButton.setText("Opcion 3");
        opcion3RadioButton.setActionCommand("op3");

        radioButtonLabel.setText("Radio Button");

        getSelectedOptionButton.setText("Get selected option");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcion3RadioButton)
                    .addComponent(opcion2RadioButton)
                    .addComponent(opcion1RadioButton)
                    .addComponent(radioButtonLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(getSelectedOptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(radioButtonLabel)
                .addGap(18, 18, 18)
                .addComponent(opcion1RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcion2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcion3RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(getSelectedOptionButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedOption() {
        String option = null;
        if (optionGroup.getSelection() != null) {
            option = optionGroup.getSelection().getActionCommand();
        }
        return option;
    }
    
    public void addGetOptionButtonActionListener(ActionListener listener) {
        this.getSelectedOptionButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getSelectedOptionButton;
    private javax.swing.JRadioButton opcion1RadioButton;
    private javax.swing.JRadioButton opcion2RadioButton;
    private javax.swing.JRadioButton opcion3RadioButton;
    private javax.swing.ButtonGroup optionGroup;
    private javax.swing.JLabel radioButtonLabel;
    // End of variables declaration//GEN-END:variables
}
