/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.radioButton;

import java.awt.event.ActionListener;

/**
 *
 * @author dides
 */
public class RadioButtonDialog extends javax.swing.JDialog {

    /**
     * Creates new form radioButtonDialog
     */
    public RadioButtonDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionGroup = new javax.swing.ButtonGroup();
        option1RadioButton = new javax.swing.JRadioButton();
        option2RadioButton = new javax.swing.JRadioButton();
        option3RadioButton = new javax.swing.JRadioButton();
        radioButtonLabel = new javax.swing.JLabel();
        getSelectedOptionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        optionGroup.add(option1RadioButton);
        option1RadioButton.setText("Option 1");
        option1RadioButton.setActionCommand("opt1");

        optionGroup.add(option2RadioButton);
        option2RadioButton.setText("Option 2");
        option2RadioButton.setActionCommand("opt2");

        optionGroup.add(option3RadioButton);
        option3RadioButton.setText("Option 3");
        option3RadioButton.setActionCommand("opt3");

        radioButtonLabel.setText("Radio Button Demo");

        getSelectedOptionButton.setText("Get selected option");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonLabel)
                    .addComponent(option1RadioButton)
                    .addComponent(option2RadioButton)
                    .addComponent(option3RadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(getSelectedOptionButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonLabel)
                .addGap(29, 29, 29)
                .addComponent(option1RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option3RadioButton)
                .addGap(18, 18, 18)
                .addComponent(getSelectedOptionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedOption() {
        String option = null;
        if (optionGroup.getSelection() != null) {
            option = optionGroup.getSelection().getActionCommand();
        }
        return option;
    }
    
    public void addGetOptionButtonActionListener(ActionListener listener) {
        this.getSelectedOptionButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getSelectedOptionButton;
    private javax.swing.JRadioButton option1RadioButton;
    private javax.swing.JRadioButton option2RadioButton;
    private javax.swing.JRadioButton option3RadioButton;
    private javax.swing.ButtonGroup optionGroup;
    private javax.swing.JLabel radioButtonLabel;
    // End of variables declaration//GEN-END:variables
}
