/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.checkBox;

import java.awt.event.ActionListener;

/**
 *
 * @author dides
 */
public class CheckBoxDialog extends javax.swing.JDialog {

    /**
     * Creates new form CheckBoxDialog
     */
    public CheckBoxDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBoxOption1 = new javax.swing.JCheckBox();
        checkBoxOption2 = new javax.swing.JCheckBox();
        checkBoxOption3 = new javax.swing.JCheckBox();
        getSelectedOptionButton = new javax.swing.JButton();
        checkBoxDemoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        checkBoxOption1.setText("Option 1");
        checkBoxOption1.setActionCommand("Opt1");

        checkBoxOption2.setText("Option 2");
        checkBoxOption2.setActionCommand("Opt2");

        checkBoxOption3.setText("Option 3");
        checkBoxOption3.setActionCommand("Opt3");

        getSelectedOptionButton.setText("Get selected option/s");

        checkBoxDemoLabel.setText("CheckBox Demo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxOption1)
                    .addComponent(checkBoxOption2)
                    .addComponent(checkBoxOption3)
                    .addComponent(checkBoxDemoLabel))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getSelectedOptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxDemoLabel)
                .addGap(25, 25, 25)
                .addComponent(checkBoxOption1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxOption2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxOption3)
                .addGap(18, 18, 18)
                .addComponent(getSelectedOptionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedOptions() {
        String selection = "";
        if (checkBoxOption1.isSelected()) {
            selection = selection.concat(checkBoxOption1.getActionCommand());
            selection = selection.concat("\n");
        }
        if (checkBoxOption2.isSelected()) {
            selection = selection.concat(checkBoxOption2.getActionCommand());
            selection = selection.concat("\n");
        }
        if (checkBoxOption3.isSelected()) {
            selection = selection.concat(checkBoxOption3.getActionCommand());
            selection = selection.concat("\n");
        }

        return selection;
    }

    public void addGetOptionButtonActionListener(ActionListener listener) {
        this.getSelectedOptionButton.addActionListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkBoxDemoLabel;
    private javax.swing.JCheckBox checkBoxOption1;
    private javax.swing.JCheckBox checkBoxOption2;
    private javax.swing.JCheckBox checkBoxOption3;
    private javax.swing.JButton getSelectedOptionButton;
    // End of variables declaration//GEN-END:variables
}
