/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.calculator;

import java.awt.event.ActionListener;

/**
 *
 * @author iglesias_nieto_rodrigo
 */
public class CalculatorJDialog extends javax.swing.JDialog {

    /**
     * Creates new form CalculatorJDialog
     */
    public CalculatorJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTextField = new javax.swing.JTextField();
        clearDisplayButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        numberSevenButton = new javax.swing.JButton();
        numberEightButton = new javax.swing.JButton();
        numberNineButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        substractButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        numberFourButton = new javax.swing.JButton();
        numberFiveButton = new javax.swing.JButton();
        numberSixButton = new javax.swing.JButton();
        numberOneButton = new javax.swing.JButton();
        numberTwoButton = new javax.swing.JButton();
        numberThreeButton = new javax.swing.JButton();
        numberZeroButton = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        displayTextField.setEditable(false);
        displayTextField.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setText("0");

        clearDisplayButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        clearDisplayButton.setText("AC");

        divideButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        divideButton.setText("/");

        numberSevenButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberSevenButton.setText("7");

        numberEightButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberEightButton.setText("8");

        numberNineButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberNineButton.setText("9");

        multiplyButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        multiplyButton.setText("x");

        substractButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        substractButton.setText("-");

        addButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        addButton.setText("+");

        equalButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        equalButton.setText("=");

        numberFourButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberFourButton.setText("4");

        numberFiveButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberFiveButton.setText("5");

        numberSixButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberSixButton.setText("6");

        numberOneButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberOneButton.setText("1");

        numberTwoButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberTwoButton.setText("2");

        numberThreeButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberThreeButton.setText("3");

        numberZeroButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        numberZeroButton.setText("0");

        decimalButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        decimalButton.setText("·");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numberFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(numberFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(clearDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(substractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(substractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // FUNCIONES
    public String getDisplayText() {
        return displayTextField.getText();
    }

    public void updateDisplay(String text) {
        this.displayTextField.setText(text);
    }

    public void disableDecimalButton() {
        this.decimalButton.setEnabled(false);
    }

    public void enableDecimalButton() {
        this.decimalButton.setEnabled(true);
    }

    // OPERADORES
    public void setAddButtonActionListener(ActionListener listener) {
        this.addButton.addActionListener(listener);
    }

    public void setSubstractButtonActionListener(ActionListener listener) {
        this.substractButton.addActionListener(listener);
    }

    public void setMultiplyButtonActionListener(ActionListener listener) {
        this.multiplyButton.addActionListener(listener);
    }

    public void setDivideButtonActionListener(ActionListener listener) {
        this.divideButton.addActionListener(listener);
    }

    public void setClearDisplayButtonActionListener(ActionListener listener) {
        this.clearDisplayButton.addActionListener(listener);
    }

    public void setDecimalButtonActionListener(ActionListener listener) {
        this.decimalButton.addActionListener(listener);
    }

    public void setEqualButtonActionListener(ActionListener listener) {
        this.equalButton.addActionListener(listener);
    }

    public void setMultplyButtonActionListener(ActionListener listener) {
        this.multiplyButton.addActionListener(listener);
    }

    // NUMEROS
    public void setNumberZeroButtonActionListener(ActionListener listener) {
        this.numberZeroButton.addActionListener(listener);
    }

    public void setNumberOneButtonActionListener(ActionListener listener) {
        this.numberOneButton.addActionListener(listener);
    }

    public void setNumberTwoButtonActionListener(ActionListener listener) {
        this.numberTwoButton.addActionListener(listener);
    }

    public void setNumberThreeButtonActionListener(ActionListener listener) {
        this.numberThreeButton.addActionListener(listener);
    }

    public void setNumberFourButtonActionListener(ActionListener listener) {
        this.numberFourButton.addActionListener(listener);
    }

    public void setNumberFiveButtonActionListener(ActionListener listener) {
        this.numberFiveButton.addActionListener(listener);
    }

    public void setNumberSixButtonActionListener(ActionListener listener) {
        this.numberSixButton.addActionListener(listener);
    }

    public void setNumberSevenButtonActionListener(ActionListener listener) {
        this.numberSevenButton.addActionListener(listener);
    }

    public void setNumberEightButtonActionListener(ActionListener listener) {
        this.numberEightButton.addActionListener(listener);
    }

    public void setNumberNineButtonActionListener(ActionListener listener) {
        this.numberNineButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearDisplayButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton numberEightButton;
    private javax.swing.JButton numberFiveButton;
    private javax.swing.JButton numberFourButton;
    private javax.swing.JButton numberNineButton;
    private javax.swing.JButton numberOneButton;
    private javax.swing.JButton numberSevenButton;
    private javax.swing.JButton numberSixButton;
    private javax.swing.JButton numberThreeButton;
    private javax.swing.JButton numberTwoButton;
    private javax.swing.JButton numberZeroButton;
    private javax.swing.JButton substractButton;
    // End of variables declaration//GEN-END:variables
}
