/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.salonPalace;

/**
 *
 * @author iglesias_nieto_rodrigo
 */
public class SalonPalaceDialog extends javax.swing.JDialog {

    /**
     * Creates new form SalonPalaceDialog
     */
    public SalonPalaceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTypeButtonGroup = new javax.swing.ButtonGroup();
        kitchenOptionButtonGroup = new javax.swing.ButtonGroup();
        salonPalaceLabel = new javax.swing.JLabel();
        personalDataPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        bookingDataPanel = new javax.swing.JPanel();
        eventTypeLabel = new javax.swing.JLabel();
        feastRadioButton = new javax.swing.JRadioButton();
        conferenceRadioButton = new javax.swing.JRadioButton();
        congressRadioButton = new javax.swing.JRadioButton();
        attendeeNumber = new javax.swing.JLabel();
        attendeeSpinner = new javax.swing.JSpinner();
        kitchenLabel = new javax.swing.JLabel();
        buffetRadioButton = new javax.swing.JRadioButton();
        menuRadioButton = new javax.swing.JRadioButton();
        chefRadioButton = new javax.swing.JRadioButton();
        noServiceRadioButton = new javax.swing.JRadioButton();
        attendeeRoomsLabel = new javax.swing.JLabel();
        attendeeRoomCheckBox = new javax.swing.JCheckBox();
        sendPetitionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        salonPalaceLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        salonPalaceLabel.setText("SALON PALACE");

        personalDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        personalDataPanel.setName("Datos personales"); // NOI18N

        nameLabel.setText("Nombre");

        emailLabel.setText("Email");

        phoneNumberLabel.setText("Telefono");

        javax.swing.GroupLayout personalDataPanelLayout = new javax.swing.GroupLayout(personalDataPanel);
        personalDataPanel.setLayout(personalDataPanelLayout);
        personalDataPanelLayout.setHorizontalGroup(
            personalDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personalDataPanelLayout.setVerticalGroup(
            personalDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDataPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(personalDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personalDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(personalDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberLabel)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bookingDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reserva"));

        eventTypeLabel.setText("Tipo de evento:");

        eventTypeButtonGroup.add(feastRadioButton);
        feastRadioButton.setText("Banquete");

        eventTypeButtonGroup.add(conferenceRadioButton);
        conferenceRadioButton.setText("Jornada");

        eventTypeButtonGroup.add(congressRadioButton);
        congressRadioButton.setText("Congreso");

        attendeeNumber.setText("Número de asistentes");

        kitchenLabel.setText("Cocina:");

        kitchenOptionButtonGroup.add(buffetRadioButton);
        buffetRadioButton.setText("Buffet");

        kitchenOptionButtonGroup.add(menuRadioButton);
        menuRadioButton.setText("Carta");

        kitchenOptionButtonGroup.add(chefRadioButton);
        chefRadioButton.setText("Cita con el chef");
        chefRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefRadioButtonActionPerformed(evt);
            }
        });

        kitchenOptionButtonGroup.add(noServiceRadioButton);
        noServiceRadioButton.setText("Sin servicio");
        noServiceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noServiceRadioButtonActionPerformed(evt);
            }
        });

        attendeeRoomsLabel.setText("¿Se necesitarán habitaciones para los asistentes?");

        attendeeRoomCheckBox.setText("Sí");

        javax.swing.GroupLayout bookingDataPanelLayout = new javax.swing.GroupLayout(bookingDataPanel);
        bookingDataPanel.setLayout(bookingDataPanelLayout);
        bookingDataPanelLayout.setHorizontalGroup(
            bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingDataPanelLayout.createSequentialGroup()
                        .addComponent(kitchenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buffetRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(menuRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chefRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noServiceRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bookingDataPanelLayout.createSequentialGroup()
                        .addComponent(attendeeRoomsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attendeeRoomCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bookingDataPanelLayout.createSequentialGroup()
                        .addComponent(eventTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(feastRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conferenceRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(congressRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(attendeeNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attendeeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        bookingDataPanelLayout.setVerticalGroup(
            bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feastRadioButton)
                    .addComponent(conferenceRadioButton)
                    .addComponent(congressRadioButton)
                    .addComponent(eventTypeLabel)
                    .addComponent(attendeeNumber)
                    .addComponent(attendeeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitchenLabel)
                    .addComponent(buffetRadioButton)
                    .addComponent(menuRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chefRadioButton)
                    .addComponent(noServiceRadioButton))
                .addGap(18, 18, 18)
                .addGroup(bookingDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendeeRoomsLabel)
                    .addComponent(attendeeRoomCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sendPetitionButton.setText("Enviar petición");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendPetitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(salonPalaceLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personalDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookingDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(salonPalaceLabel)
                .addGap(18, 18, 18)
                .addComponent(personalDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendPetitionButton)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chefRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefRadioButtonActionPerformed

    private void noServiceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noServiceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noServiceRadioButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendeeNumber;
    private javax.swing.JCheckBox attendeeRoomCheckBox;
    private javax.swing.JLabel attendeeRoomsLabel;
    private javax.swing.JSpinner attendeeSpinner;
    private javax.swing.JPanel bookingDataPanel;
    private javax.swing.JRadioButton buffetRadioButton;
    private javax.swing.JRadioButton chefRadioButton;
    private javax.swing.JRadioButton conferenceRadioButton;
    private javax.swing.JRadioButton congressRadioButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.ButtonGroup eventTypeButtonGroup;
    private javax.swing.JLabel eventTypeLabel;
    private javax.swing.JRadioButton feastRadioButton;
    private javax.swing.JLabel kitchenLabel;
    private javax.swing.ButtonGroup kitchenOptionButtonGroup;
    private javax.swing.JRadioButton menuRadioButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton noServiceRadioButton;
    private javax.swing.JPanel personalDataPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel salonPalaceLabel;
    private javax.swing.JButton sendPetitionButton;
    // End of variables declaration//GEN-END:variables
}
