/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author iglesias_nieto_rodrigo
 */
public class CalculadoraJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTextField = new javax.swing.JTextField();
        zeroButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        sieteButton = new javax.swing.JButton();
        nueveButton = new javax.swing.JButton();
        multiplicacionButton = new javax.swing.JButton();
        ochoButton = new javax.swing.JButton();
        cuatroButton = new javax.swing.JButton();
        cincoButton = new javax.swing.JButton();
        seisButton = new javax.swing.JButton();
        restaButton = new javax.swing.JButton();
        unoButton = new javax.swing.JButton();
        dosButton = new javax.swing.JButton();
        tresButton = new javax.swing.JButton();
        igualButton = new javax.swing.JButton();
        borrarButton = new javax.swing.JButton();
        sumaButton = new javax.swing.JButton();
        calculoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        displayTextField.setEditable(false);
        displayTextField.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setText("0");
        displayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTextFieldActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        divisionButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        divisionButton.setText("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        sieteButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        sieteButton.setText("7");
        sieteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteButtonActionPerformed(evt);
            }
        });

        nueveButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        nueveButton.setText("9");
        nueveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveButtonActionPerformed(evt);
            }
        });

        multiplicacionButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        multiplicacionButton.setText("x");
        multiplicacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionButtonActionPerformed(evt);
            }
        });

        ochoButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        ochoButton.setText("8");
        ochoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoButtonActionPerformed(evt);
            }
        });

        cuatroButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        cuatroButton.setText("4");
        cuatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroButtonActionPerformed(evt);
            }
        });

        cincoButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        cincoButton.setText("5");
        cincoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoButtonActionPerformed(evt);
            }
        });

        seisButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        seisButton.setText("6");
        seisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisButtonActionPerformed(evt);
            }
        });

        restaButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        restaButton.setText("-");
        restaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaButtonActionPerformed(evt);
            }
        });

        unoButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        unoButton.setText("1");
        unoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoButtonActionPerformed(evt);
            }
        });

        dosButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        dosButton.setText("2");
        dosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosButtonActionPerformed(evt);
            }
        });

        tresButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        tresButton.setText("3");
        tresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresButtonActionPerformed(evt);
            }
        });

        igualButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        igualButton.setText("=");
        igualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualButtonActionPerformed(evt);
            }
        });

        borrarButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        borrarButton.setText("AC");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        sumaButton.setFont(new java.awt.Font("Ubuntu Mono", 0, 36)); // NOI18N
        sumaButton.setText("+");
        sumaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(calculoLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(borrarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(unoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(dosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(sieteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ochoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(nueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(3, 3, 3)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(igualButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sumaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(restaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(divisionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(multiplicacionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(calculoLabel)
                .addGap(24, 24, 24)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(igualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        guardarNumero("/");

    }//GEN-LAST:event_divisionButtonActionPerformed

    private void multiplicacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionButtonActionPerformed
        guardarNumero("*");
    }//GEN-LAST:event_multiplicacionButtonActionPerformed

    private void restaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaButtonActionPerformed
        guardarNumero("-");
    }//GEN-LAST:event_restaButtonActionPerformed

    private void sumaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaButtonActionPerformed
        guardarNumero("+");
    }//GEN-LAST:event_sumaButtonActionPerformed

    private void cuatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroButtonActionPerformed
        updateDisplay("4");
    }//GEN-LAST:event_cuatroButtonActionPerformed

    private void unoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoButtonActionPerformed
        updateDisplay("1");
    }//GEN-LAST:event_unoButtonActionPerformed

    private void tresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresButtonActionPerformed
        updateDisplay("3");
    }//GEN-LAST:event_tresButtonActionPerformed

    private void displayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTextFieldActionPerformed

    private void dosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosButtonActionPerformed
        updateDisplay("2");
    }//GEN-LAST:event_dosButtonActionPerformed

    private void cincoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoButtonActionPerformed
        updateDisplay("5");
    }//GEN-LAST:event_cincoButtonActionPerformed

    private void seisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisButtonActionPerformed
        updateDisplay("6");
    }//GEN-LAST:event_seisButtonActionPerformed

    private void sieteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteButtonActionPerformed
        updateDisplay("7");
    }//GEN-LAST:event_sieteButtonActionPerformed

    private void ochoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoButtonActionPerformed
        updateDisplay("8");
    }//GEN-LAST:event_ochoButtonActionPerformed

    private void nueveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveButtonActionPerformed
        updateDisplay("9");
    }//GEN-LAST:event_nueveButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        updateDisplay("0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        clearDisplay();
        resetNumbers();
        updateDisplay("0");
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void igualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualButtonActionPerformed
        guardarNumero(".");
        switch (operador) {
            case "+":
                updateDisplay(String.valueOf(primerNumero + segundoNumero));
                primerNumero = (primerNumero + segundoNumero);
                break;
            case "-":
                updateDisplay(String.valueOf(primerNumero - segundoNumero));
                primerNumero = primerNumero - segundoNumero;
                break;
            case "*":
                updateDisplay(String.valueOf(primerNumero * segundoNumero));
                primerNumero = primerNumero * segundoNumero;
                break;
            case "/":
                if (primerNumero % segundoNumero == 0) {
                    updateDisplay(String.valueOf(primerNumero / segundoNumero));
                    primerNumero = (primerNumero/segundoNumero);
                } else {
                    updateDisplay(String.format("%.2f", (primerNumero + 0.0) / segundoNumero));
                }
        }
    }//GEN-LAST:event_igualButtonActionPerformed

    /**
     * FUNCIONES
     */
    private void updateDisplay(String txt) {
        String texto = displayTextField.getText();
        if (texto.equals("0")) {
            clearDisplay();
            displayTextField.setText(txt);
        } else {
            displayTextField.setText(texto + txt);
        }
    }

    private void clearDisplay() {
        displayTextField.setText("");
    }

    private void resetNumbers() {
        primerNumero = null;
        segundoNumero = null;
    }

    private void guardarNumero(String op) {
        if (primerNumero == null) {
            primerNumero = Integer.parseInt(displayTextField.getText());
        } else if (!ultimoOperador.equals(".")) {
            segundoNumero = Integer.parseInt(displayTextField.getText());
        }
        System.out.println("primerNumero: " + primerNumero);
        System.out.println("segundoNumero: " + segundoNumero);
        clearDisplay();
        if (!op.equals(".")) {
            operador = op;
        }
        ultimoOperador = op;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJFrame().setVisible(true);
            }
        });
    }

    /*VARIABLES*/
    private Integer primerNumero;
    private Integer segundoNumero;
    private String operador;
    private String ultimoOperador;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButton;
    private javax.swing.JLabel calculoLabel;
    private javax.swing.JButton cincoButton;
    private javax.swing.JButton cuatroButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton dosButton;
    private javax.swing.JButton igualButton;
    private javax.swing.JButton multiplicacionButton;
    private javax.swing.JButton nueveButton;
    private javax.swing.JButton ochoButton;
    private javax.swing.JButton restaButton;
    private javax.swing.JButton seisButton;
    private javax.swing.JButton sieteButton;
    private javax.swing.JButton sumaButton;
    private javax.swing.JButton tresButton;
    private javax.swing.JButton unoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
