/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clock.AlarmEvent;
import clock.IAlarmListener;
import java.awt.event.ActionListener;

/**
 *
 * @author dides
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainClockBean = new clock.ClockBean();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        manageDataMenuItem = new javax.swing.JMenuItem();
        manageComputersMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        notificationsMenu = new javax.swing.JMenu();
        notificationsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        manageDataMenuItem.setText("Manage data...");
        fileMenu.add(manageDataMenuItem);

        manageComputersMenuItem.setText("Manage computers...");
        fileMenu.add(manageComputersMenuItem);

        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        notificationsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alert.png"))); // NOI18N

        notificationsMenuItem.setText("Notifications...");
        notificationsMenu.add(notificationsMenuItem);

        menuBar.add(notificationsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(mainClockBean, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(mainClockBean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setQuitMenuItemListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }

    public void setManageDataMenuItemListener(ActionListener listener) {
        this.manageDataMenuItem.addActionListener(listener);
    }

    public void setManageComputersMenuItemListener(ActionListener listener) {
        this.manageComputersMenuItem.addActionListener(listener);
    }

    public void setNotificationsMenuItemListener(ActionListener listener) {
        this.notificationsMenuItem.addActionListener(listener);
    }

    public boolean isAlarmEnabled() {
        return mainClockBean.isEnableAlarm();
    }

    public boolean isClockMode24() {
        return mainClockBean.isMode24();
    }

    public int getAlertHour() {
        return mainClockBean.getHourAlarm();
    }
    
    public int getAlertMinutes() {
        return mainClockBean.getMinutesAlarm();
    }
    
    public String getAlarmMessage() {
        return mainClockBean.getMessage();
    }
    
    public void setClockMode(boolean mode) {
        this.mainClockBean.setMode24(mode);
    }
    
    public void setAlertHour(int hour) {
        this.mainClockBean.setHourAlarm(hour);
    }
    
    public void setAlertMinutes(int minutes) {
        this.mainClockBean.setMinutesAlarm(minutes);
    }
    
    public void setAlertMessage(String message) {
        this.mainClockBean.setMessage(message);
    }

    public void setAlertEnable(boolean enableAlarm) {
        this.mainClockBean.setEnableAlarm(enableAlarm);
    }
    
    public void setClockBeanIAlarmListener(IAlarmListener listener) {
        this.mainClockBean.addAlarmListener(listener);
    }
    
    public void removeClockBeanAlarmListener(IAlarmListener receptor) {
        mainClockBean.removeAlarmListener(receptor);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private clock.ClockBean mainClockBean;
    private javax.swing.JMenuItem manageComputersMenuItem;
    private javax.swing.JMenuItem manageDataMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu notificationsMenu;
    private javax.swing.JMenuItem notificationsMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    // End of variables declaration//GEN-END:variables
}
