/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clock.AlarmEvent;
import clock.IAlarmListener;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author dides
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.getConentPane().setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        manageDataMenuItem = new javax.swing.JMenuItem();
        manageComputersMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        generateReportMenuItem = new javax.swing.JMenuItem();
        notificationsMenu = new javax.swing.JMenu();
        notificationsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        manageDataMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        manageDataMenuItem.setText("Manage data...");
        fileMenu.add(manageDataMenuItem);

        manageComputersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        manageComputersMenuItem.setText("Manage computers...");
        fileMenu.add(manageComputersMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        reportsMenu.setText("Reports");

        generateReportMenuItem.setText("Generate report...");
        reportsMenu.add(generateReportMenuItem);

        menuBar.add(reportsMenu);

        notificationsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alert.png"))); // NOI18N

        notificationsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        notificationsMenuItem.setText("Notifications...");
        notificationsMenu.add(notificationsMenuItem);

        menuBar.add(notificationsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setQuitMenuItemListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }
    
    public void setManageDataMenuItemListener(ActionListener listener) {
        this.manageDataMenuItem.addActionListener(listener);
    }
    
    public void setManageComputersMenuItemListener(ActionListener listener) {
        this.manageComputersMenuItem.addActionListener(listener);
    }
    
    public void setNotificationsMenuItemListener(ActionListener listener) {
        this.notificationsMenuItem.addActionListener(listener);
    }
    
    public void setGenerateReportMenuItemListener(ActionListener listener) {
        this.generateReportMenuItem.addActionListener(listener);
    }
    
    public Component getConentPane() {
        return this.getContentPane();
    }

    // ALARM
    /*public boolean isAlarmEnabled() {
        return mainClockBean.isEnableAlarm();
    }
    
    public boolean isClockMode24() {
        return mainClockBean.isMode24();
    }
    
    public int getAlertHour() {
        return mainClockBean.getHourAlarm();
    }
    
    public int getAlertMinutes() {
        return mainClockBean.getMinutesAlarm();
    }
    
    public String getAlarmMessage() {
        return mainClockBean.getMessage();
    }
    
    public void setClockMode(boolean mode) {
        this.mainClockBean.setMode24(mode);
    }
    
    public void setAlertHour(int hour) {
        this.mainClockBean.setHourAlarm(hour);
    }
    
    public void setAlertMinutes(int minutes) {
        this.mainClockBean.setMinutesAlarm(minutes);
    }
    
    public void setAlertMessage(String message) {
        this.mainClockBean.setMessage(message);
    }
    
    public void setAlertEnable(boolean enableAlarm) {
        this.mainClockBean.setEnableAlarm(enableAlarm);
    }
    
    public void setClockBeanIAlarmListener(IAlarmListener listener) {
        this.mainClockBean.addAlarmListener(listener);
    }
    
    public void removeClockBeanAlarmListener(IAlarmListener receptor) {
        mainClockBean.removeAlarmListener(receptor);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem generateReportMenuItem;
    private javax.swing.JMenuItem manageComputersMenuItem;
    private javax.swing.JMenuItem manageDataMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu notificationsMenu;
    private javax.swing.JMenuItem notificationsMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenu reportsMenu;
    // End of variables declaration//GEN-END:variables
}
