/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.notifications;

import java.awt.event.ActionListener;

/**
 *
 * @author iglesias_nieto_rodrigo
 */
public class NotificationsDialog extends javax.swing.JDialog {

    /**
     * Creates new form NotificationsDialog
     */
    public NotificationsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockModeButtonGroup = new javax.swing.ButtonGroup();
        clockModeLabel = new javax.swing.JLabel();
        mode24RadioButton = new javax.swing.JRadioButton();
        mode12RadioButton = new javax.swing.JRadioButton();
        alertTimeLabel = new javax.swing.JLabel();
        alertHourSpinner = new javax.swing.JSpinner();
        alertMinuteSpinner = new javax.swing.JSpinner();
        messageLabel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        setClockButton = new javax.swing.JButton();
        disableAlarmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clockModeLabel.setText("Clock mode:");

        clockModeButtonGroup.add(mode24RadioButton);
        mode24RadioButton.setText("24H");

        clockModeButtonGroup.add(mode12RadioButton);
        mode12RadioButton.setText("12H");

        alertTimeLabel.setText("Alert time:");

        alertHourSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        alertMinuteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        messageLabel.setText("Message:");

        setClockButton.setText("Set clock");

        disableAlarmButton.setText("Disable Alarm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alertTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alertHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alertMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clockModeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(mode24RadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(mode12RadioButton))
                    .addComponent(setClockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disableAlarmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockModeLabel)
                    .addComponent(mode24RadioButton)
                    .addComponent(mode12RadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alertTimeLabel)
                    .addComponent(alertHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(setClockButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(disableAlarmButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setClockButtonListener(ActionListener listener) {
        this.setClockButton.addActionListener(listener);
    }

    public void setDisableAlarmListener(ActionListener listener) {
        this.disableAlarmButton.addActionListener(listener);
    }
    
    public boolean isMode24() {
        return this.mode24RadioButton.isSelected();
    }
    
    public int getHourAlertTime() {
        return (int) alertHourSpinner.getValue();
    }
    
    public int getMinuteAlertTime() {
        return (int) alertMinuteSpinner.getValue();
    }
    
    public String getMessage() {
        return messageTextField.getText();
    }
    
    public void setMode24(boolean mode) {
        if (mode) {
            mode24RadioButton.setSelected(true);
        } else {
            mode12RadioButton.setSelected(true);
        }
    }
    
    public void setAlertHourSpinner(int hour) {
        this.alertHourSpinner.setValue(hour);
    }
    
    public void setAlertMinuteSpinner(int minute) {
        this.alertMinuteSpinner.setValue(minute);
    }
    
    public void setMessage(String message) {
        this.messageTextField.setText(message);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner alertHourSpinner;
    private javax.swing.JSpinner alertMinuteSpinner;
    private javax.swing.JLabel alertTimeLabel;
    private javax.swing.ButtonGroup clockModeButtonGroup;
    private javax.swing.JLabel clockModeLabel;
    private javax.swing.JButton disableAlarmButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JRadioButton mode12RadioButton;
    private javax.swing.JRadioButton mode24RadioButton;
    private javax.swing.JButton setClockButton;
    // End of variables declaration//GEN-END:variables
}
